// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNER3d8ZpRQqoCHWp66uHmjbLawT-9kg',
    appId: '1:658583987580:web:970a9643bf0dc6cf1930f9',
    messagingSenderId: '658583987580',
    projectId: 'chakshufallsense',
    authDomain: 'chakshufallsense.firebaseapp.com',
    databaseURL: 'https://chakshufallsense-default-rtdb.firebaseio.com',
    storageBucket: 'chakshufallsense.firebasestorage.app',
    measurementId: 'G-40T7G5L08Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6QNr8F0vfsNCgE2BwkSxlgNZxQBjTETw',
    appId: '1:658583987580:android:77d0dc0fa3693c381930f9',
    messagingSenderId: '658583987580',
    projectId: 'chakshufallsense',
    databaseURL: 'https://chakshufallsense-default-rtdb.firebaseio.com',
    storageBucket: 'chakshufallsense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLKKM4aJUuCU5jiDtI61zjqEcre5Z0ng',
    appId: '1:658583987580:ios:885c9c99f9e6d44f1930f9',
    messagingSenderId: '658583987580',
    projectId: 'chakshufallsense',
    databaseURL: 'https://chakshufallsense-default-rtdb.firebaseio.com',
    storageBucket: 'chakshufallsense.firebasestorage.app',
    iosBundleId: 'com.example.fallSenseXMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLKKM4aJUuCU5jiDtI61zjqEcre5Z0ng',
    appId: '1:658583987580:ios:885c9c99f9e6d44f1930f9',
    messagingSenderId: '658583987580',
    projectId: 'chakshufallsense',
    databaseURL: 'https://chakshufallsense-default-rtdb.firebaseio.com',
    storageBucket: 'chakshufallsense.firebasestorage.app',
    iosBundleId: 'com.example.fallSenseXMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQNER3d8ZpRQqoCHWp66uHmjbLawT-9kg',
    appId: '1:658583987580:web:6a6bc087e71ab5061930f9',
    messagingSenderId: '658583987580',
    projectId: 'chakshufallsense',
    authDomain: 'chakshufallsense.firebaseapp.com',
    databaseURL: 'https://chakshufallsense-default-rtdb.firebaseio.com',
    storageBucket: 'chakshufallsense.firebasestorage.app',
    measurementId: 'G-RVH3TSKQCM',
  );
}
